In [1]:
import numpy as np

In [2]:
data = [23,14,56,72,90]
np.mean(data)

np.float64(51.0)

In [3]:
np.min(data)

np.int64(14)

In [4]:
a=[1,3,5,7]
b=[4,5,6,7]
arr1=np.array(a)
arr2=np.array(b)

In [5]:
arr2

array([4, 5, 6, 7])

In [6]:
arr1 * arr2

array([ 4, 15, 30, 49])

In [7]:
arr1.ndim

1

In [8]:
arr1.shape

(4,)

In [9]:
arr1.dtype

dtype('int64')

In [10]:
 arr3=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
arr3.ndim

2

In [12]:
arr3.shape

(3, 3)

In [13]:
np.arange(0,10,1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(10,1,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2])

In [15]:
np.random.randint(10,100,5)

array([11, 68, 16, 44, 20], dtype=int32)

In [16]:
np.random.uniform(10,100,50)

array([87.03675169, 10.03128154, 63.98199809, 91.76978499, 69.87269268,
       74.99106438, 40.66802728, 78.91830822, 77.92411796, 90.31787942,
       37.96338526, 25.20289667, 96.35305962, 40.11598163, 48.04828319,
       47.6054928 , 57.35655414, 85.47308917, 69.56486184, 30.96401509,
       10.08344766, 73.38334309, 15.87235791, 74.98371209, 73.73517165,
       62.15805593, 85.77019093, 17.20968925, 76.41649004, 49.0432907 ,
       56.00131937, 26.50628417, 79.59919248, 43.37888945, 55.81431509,
       69.49874502, 93.4696429 , 50.74838398, 42.48308502, 52.46268795,
       91.96282115, 97.24742002, 38.94947893, 76.92925529, 17.20848165,
       12.51030326, 17.51819212, 87.71788521, 20.34616702, 49.1923227 ])

In [17]:
np.random.rand(100)

array([0.93850926, 0.72660634, 0.32042173, 0.06745045, 0.09424681,
       0.52482059, 0.66606908, 0.12675446, 0.62622822, 0.60758109,
       0.80774392, 0.15258218, 0.97919685, 0.44535537, 0.11063358,
       0.37653484, 0.12075103, 0.90472115, 0.69242804, 0.29969506,
       0.65341186, 0.58266694, 0.21229226, 0.05164892, 0.93945968,
       0.21867076, 0.23075826, 0.32701856, 0.66162582, 0.56327222,
       0.39177373, 0.72231429, 0.73724692, 0.14454963, 0.9841594 ,
       0.10125603, 0.68494116, 0.99544307, 0.46635129, 0.32463998,
       0.40542839, 0.78857153, 0.22858358, 0.02362044, 0.76570429,
       0.98046266, 0.47569246, 0.8880834 , 0.32967103, 0.63468662,
       0.11340182, 0.1193121 , 0.15267389, 0.91683138, 0.96514356,
       0.98308093, 0.63619143, 0.14036027, 0.88703766, 0.99979133,
       0.77133945, 0.6150559 , 0.37122662, 0.53342929, 0.0100808 ,
       0.53409758, 0.97315475, 0.87539811, 0.49654001, 0.2068065 ,
       0.14782679, 0.87255259, 0.72346794, 0.44107917, 0.70455

In [18]:
np.random.randint(10,100,12).reshape(4,3)

array([[40, 89, 37],
       [17, 39, 25],
       [43, 92, 30],
       [15, 65, 45]], dtype=int32)

In [19]:
r=45.7
np.floor(r)

np.float64(45.0)

In [20]:
np.ceil(r)

np.float64(46.0)

In [21]:
z=np.random.randint(1,100,12)

In [22]:
z=sorted(z)
z

[np.int32(4),
 np.int32(12),
 np.int32(19),
 np.int32(35),
 np.int32(35),
 np.int32(38),
 np.int32(62),
 np.int32(63),
 np.int32(73),
 np.int32(84),
 np.int32(93),
 np.int32(98)]

In [23]:
np.percentile(z,75)

np.float64(75.75)

In [24]:
import pandas as pd

In [25]:
renewable_sources =['solar','wind','hydropower','geothermal','biomass']

data = {
    "project":['solar farm','wind turbine','hydropower','solar roof','geothermal plant'],
    "technology":['solar','wind','hydro','solar','geothermal'],
    "capacity (Mw)":[150,300,200,50,100],
    "cost (Million$)":[200,400,350,100,250],
    "location":["california","texas","washington","nevada","chicago"],
    "completion year":[2023,2024,2022,2025,2023]
}

In [26]:
#create a pandas series for renewable energy resources
renewable_series=pd.Series(renewable_sources)
print("renewable energy sources are:")
print(renewable_series)

renewable energy sources are:
0         solar
1          wind
2    hydropower
3    geothermal
4       biomass
dtype: object


In [27]:
#create a Dataframe for green tech projects
df =pd.DataFrame(data)
print("green technology projects dataframe:")
print(df)

green technology projects dataframe:
            project  technology  capacity (Mw)  cost (Million$)    location  \
0        solar farm       solar            150              200  california   
1      wind turbine        wind            300              400       texas   
2        hydropower       hydro            200              350  washington   
3        solar roof       solar             50              100      nevada   
4  geothermal plant  geothermal            100              250     chicago   

   completion year  
0             2023  
1             2024  
2             2022  
3             2025  
4             2023  


In [28]:
df['project']

0          solar farm
1        wind turbine
2          hydropower
3          solar roof
4    geothermal plant
Name: project, dtype: object

In [29]:
print(df['project'])

0          solar farm
1        wind turbine
2          hydropower
3          solar roof
4    geothermal plant
Name: project, dtype: object


In [30]:
#want to print only high capacity projects (> 100 MW)
hcp =df[df['capacity (Mw)'] > 100]
hcp

project technology  capacity (Mw)  cost (Million$)    location  \
0    solar farm      solar            150              200  california   
1  wind turbine       wind            300              400       texas   
2    hydropower      hydro            200              350  washington   

   completion year  
0             2023  
1             2024  
2             2022

In [31]:
df['capacity (Mw)'] > 100

0     True
1     True
2     True
3    False
4    False
Name: capacity (Mw), dtype: bool

In [34]:
#aggregation
total_capacity = df["capacity (Mw)"].sum()
total_cost =df["cost (Million$)"].sum()
print("the total capacity of all the projects are: ",total_capacity)
print("the total cost of the projects: ",total_cost)

the total capacity of all the projects are:  800
the total cost of the projects:  1300


In [35]:
#grouping of data
grouped_data = df.groupby("technology")["capacity (Mw)"].sum()
grouped_data

technology
geothermal    100
hydro         200
solar         200
wind          300
Name: capacity (Mw), dtype: int64

## day3: Numpy

In [36]:
energy_consumption = np.array([1200,3400,2900,1800,2500])
print("energy consumption in mWh for different energy sources:")
energy_consumption

energy consumption in mWh for different energy sources:


array([1200, 3400, 2900, 1800, 2500])

In [38]:
# calculate the total energy consumption
total_consumption =np.sum(energy_consumption)
print(f'the total energy consumption is :{total_consumption} MWh')


the total energy consumption is :11800 MWh


In [39]:
# calculate the mean energy consumption
mean_consumption = np.mean(energy_consumption)
print(f'the mean energy consumption is {mean_consumption} MWh')

the mean energy consumption is 2360.0 MWh


In [40]:
# calculate the standard deviation of energy consumptiom
std_ec = np.std(energy_consumption)
std_ec

np.float64(781.2809993849844)

In [41]:
print(f'the standard deviation for energy conservation is : {std_ec} MWh')

the standard deviation for energy conservation is : 781.2809993849844 MWh


In [42]:
#reshape the array
reshaped_array = energy_consumption.reshape((5,1))
print('reshaped array is:')
print(reshaped_array)

reshaped array is:
[[1200]
 [3400]
 [2900]
 [1800]
 [2500]]


## data preprocessing

In [43]:
import numpy as np
import pandas as pd

# sample data with missing values
data ={
    "energy source":['solar','wind','hydropower','geothermal','biomass','nuclear'],
    "energy consumption (MWh)":[1200,np.nan,2900,np.nan,2500,3200],
    "cost (millions $)":[200,400,np.nan,150,250,np.nan]
}

In [44]:
#create a dataframe
df = pd.DataFrame(data)
print(df)

  energy source  energy consumption (MWh)  cost (millions $)
0         solar                    1200.0              200.0
1          wind                       NaN              400.0
2    hydropower                    2900.0                NaN
3    geothermal                       NaN              150.0
4       biomass                    2500.0              250.0
5       nuclear                    3200.0                NaN


## handling missing values
- removing (drop) mv
- impute(fill) mv -mean

In [45]:
# remove rows with missing values
cleaned_df = df.dropna()
cleaned_df

energy source  energy consumption (MWh)  cost (millions $)
0         solar                    1200.0              200.0
4       biomass                    2500.0              250.0

## imputation - to add or fill
- with mean
- forward/backward filling

In [46]:
# impute missing values with the mean for energy consumption
df['energy consumption (MWh)'].fillna(df['energy consumption (MWh)'].mean(), inplace=True)
df['cost (millions $)'].fillna(df['cost (millions $)'].mean(), inplace=True)
df

C:\Users\singh\AppData\Local\Temp\ipykernel_10008\2423531713.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['energy consumption (MWh)'].fillna(df['energy consumption (MWh)'].mean(), inplace=True)
C:\Users\singh\AppData\Local\Temp\ipykernel_10008\2423531713.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting

energy source  energy consumption (MWh)  cost (millions $)
0         solar                    1200.0              200.0
1          wind                    2450.0              400.0
2    hydropower                    2900.0              250.0
3    geothermal                    2450.0              150.0
4       biomass                    2500.0              250.0
5       nuclear                    3200.0              250.0

In [47]:
# forward filling missing values
ff_df = df.fillna(method="ffill")
ff_df

C:\Users\singh\AppData\Local\Temp\ipykernel_10008\3819275965.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ff_df = df.fillna(method="ffill")


energy source  energy consumption (MWh)  cost (millions $)
0         solar                    1200.0              200.0
1          wind                    2450.0              400.0
2    hydropower                    2900.0              250.0
3    geothermal                    2450.0              150.0
4       biomass                    2500.0              250.0
5       nuclear                    3200.0              250.0

In [48]:
bf_df = df.fillna(method="bfill")
bf_df

C:\Users\singh\AppData\Local\Temp\ipykernel_10008\2046495999.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  bf_df = df.fillna(method="bfill")


energy source  energy consumption (MWh)  cost (millions $)
0         solar                    1200.0              200.0
1          wind                    2450.0              400.0
2    hydropower                    2900.0              250.0
3    geothermal                    2450.0              150.0
4       biomass                    2500.0              250.0
5       nuclear                    3200.0              250.0

In [51]:
# data preprocessing - normalization
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['energy consumption (MWh)', 'cost (millions $)']] = scaler.fit_transform(df[['energy consumption (MWh)', 'cost (millions $)']])
df

energy source  energy consumption (MWh)  cost (millions $)
0         solar                     0.000                0.2
1          wind                     0.625                1.0
2    hydropower                     0.850                0.4
3    geothermal                     0.625                0.0
4       biomass                     0.650                0.4
5       nuclear                     1.000                0.4

In [52]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[['energy consumption (MWh)', 'cost (millions $)']] = scaler.fit_transform(df[['energy consumption (MWh)', 'cost (millions $)']])
df

energy source  energy consumption (MWh)  cost (millions $)
0         solar             -2.005893e+00      -6.546537e-01
1          wind              3.563181e-16       1.963961e+00
2    hydropower              7.221213e-01       1.817029e-16
3    geothermal              3.563181e-16      -1.309307e+00
4       biomass              8.023570e-02       1.817029e-16
5       nuclear              1.203536e+00       1.817029e-16

## encoding - one hot encoding

In [53]:
ohe_df = pd.get_dummies(df , columns=["energy source"])
ohe_df

energy consumption (MWh)  cost (millions $)  energy source_biomass  \
0             -2.005893e+00      -6.546537e-01                  False   
1              3.563181e-16       1.963961e+00                  False   
2              7.221213e-01       1.817029e-16                  False   
3              3.563181e-16      -1.309307e+00                  False   
4              8.023570e-02       1.817029e-16                   True   
5              1.203536e+00       1.817029e-16                  False   

   energy source_geothermal  energy source_hydropower  energy source_nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False                  False   
5                     False                     False                   True   

   energy source_solar  energy source_wind  
0                 True               False  
1                False                True  
2                False               False  
3                False               False  
4                False               False  
5                False               False

In [54]:
# feature engineering 
ohe_df["consumption per million $"] = ohe_df['energy consumption (MWh)'] / ohe_df['cost (millions $)']
ohe_df

energy consumption (MWh)  cost (millions $)  energy source_biomass  \
0             -2.005893e+00      -6.546537e-01                  False   
1              3.563181e-16       1.963961e+00                  False   
2              7.221213e-01       1.817029e-16                  False   
3              3.563181e-16      -1.309307e+00                  False   
4              8.023570e-02       1.817029e-16                   True   
5              1.203536e+00       1.817029e-16                  False   

   energy source_geothermal  energy source_hydropower  energy source_nuclear  \
0                     False                     False                  False   
1                     False                     False                  False   
2                     False                      True                  False   
3                      True                     False                  False   
4                     False                     False                  False   
5                     False                     False                   True   

   energy source_solar  energy source_wind  consumption per million $  
0                 True               False               3.064052e+00  
1                False                True               1.814283e-16  
2                False               False               3.974187e+15  
3                False               False              -2.721424e-16  
4                False               False               4.415764e+14  
5                False               False               6.623646e+15